name = "how-connect-d1-with-remix"
compatibility_date = "2024-05-23"

[[d1_databases]]
binding = "DB"
preview_database_id = "XXXXXX-XXXX-XXXX-XXXXX-XXXXX"
database_name = "blog-proof"
database_id = "XXXXXX-XXXX-XXXX-XXXXX-XXXXX"
